### ISSUE TITLE
Support for ts-node?

### ISSUE THREAD

**Issue by elektronik2k5** [sloria/local-repl#20]
Hi there and thanks for making such an nice package! :bowing_man: 

I'm wondering: how complicated would it be to add support for [ts-node](https://github.com/TypeStrong/ts-node)?
Could it be as simple as allowing specifying an executable? I'm thinking of [node-dev](https://github.com/fgnass/node-dev) or [ts-node-dev](https://github.com/whitecolor/ts-node-dev).

Thanks again!

**Comment by sloria** [comment]
Thanks for the kind words. =) I'm unfamiliar with ts-node, but if it has the same interface as the `repl` module of the Node.js standard library, it should be straightforward add in. I would definitely review/merge a PR for it.

**Comment by sloria** [comment]
This issue has become stale.

If anyone wants to tackle this, I'll reopen.
