### ISSUE TITLE
Await commands do not execute if they are not the top level command.

### ISSUE THREAD

**Issue by jmoseley** [sloria/local-repl#22]
It seems that if a command contains `await`, but is not the top level command (? not sure how else to explain it) it does not execute. Here is some sample output to demonstrate. `...` means the prompt is expecting more input.

```
Node v8.9.1, local-repl 4.0.0
@scope/project-name 1.0.0
Context:
[@] > await Promise.resolve(42);
...
[@] > await Promise.resolve(42)
42
[@] > 42
42
[@] > 42;
42
[@] > console.log(await Promise.resolve(42))
...
[@] >
```

To replicate I installed (`yarn add -D local-repl`) and added a simple `.replrc.js`:

```
module.exports = {
  enableAwait: true,
  context: {
  },
};
```

Let me know if you need more information.

**Comment by sloria** [comment]
Thanks @jmoseley for reporting. This appears to be an issue with the upstream project, [async-outside](https://github.com/nfcampos/await-outside). My guess is that `await` within a function call is not being matched by this regex: https://github.com/nfcampos/await-outside/blob/206228f7e139ee82a6564803a6d4fed19de23e49/index.js#L57

 I recommend reporting the issue on the async-outside issue tracker.

**Comment by sloria** [comment]
As a workaround, you should be able to do

```js
let res = await Promise.resolve(42)
console.log(res)
```

**Comment by jmoseley** [comment]
I believe this has been fixed in `async-outside`: https://github.com/nfcampos/await-outside/pull/4

Is it possible to get this dependency updated?
